- README.md
The example codeblocks were missing appropriate syntax highlight tags making them harder to read. This PR just adds them to the README.md.
> Add syntax highlighting for all the code blocks in README.md

- src/request.ts
After 20 failed connections the prismic api stops responding. The error handler was not decrementing the running connections counter and was not processing the next request in the query
> Decrement the number of running connections after a failed request

- src/request.ts
By not properly accessing the request headers nothing was being cached (`ttl` was always assigned`undefined`).
This fixes that by accessing the header field in the standard way (see: https://developer.mozilla.org/en-US/docs/Web/API/Headers/get)
> Fix accessing headers in a non-standard way

- d.ts/ApiSearchResponse.d.ts
- d.ts/ResolvedApi.d.ts
- d.ts/client.d.ts
- src/ApiSearchResponse.ts
- src/ResolvedApi.ts
- src/client.ts
I noticed that the `Document` interface is not imported in the classes that use it. So in my TypeScript-project all the things related to this interface are broken :(
Please merge this PR asap  :+1:
> Add missing imports

- d.ts/ResolvedApi.d.ts
`isMasterRef` was described as a string, but the API returns a boolean, which made following the docs to configure in-site preview a pain because `api.refs.find(ref => ref.isMasterRef)` tries to compare a string to a boolean 😢
> Fix Ref interface

- README.md
If you include Primsic through CDN (script tag), the variable name is PrimsicJS and you can leave the require out. I've added a section to the readme in ES6 syntax.
> added documentation for including Prismic through CDN

- src/Predicates.ts
- test/predicates.js
The api is able to handle Predicates with `boolean` values (https://prismic.io/docs/rest-api/query-the-api/query-by-a-field#14_0-a-boolean-field). But the `PredicateValue` does not contain `boolean` and the `encode` method does not encode booleans.
> Feature: Adds boolean value in type PredicateValue.

- d.ts/ResolvedApi.d.ts
- d.ts/client.d.ts
- src/ResolvedApi.ts
- src/client.ts
This PR
- fixes query definition to be optional for second parameter. Currently all tests and documentation marks the second parameter as optional for `query` and `queryfirst`
- cleans up imports
- cleans up some small inconsistencies: double-quotes, spelling mistakes, semicolons
> Clean up query method definition

- src/PreviewResolver.ts
- src/ResolvedApi.ts
- src/documents.ts
Instantiating the API with a routes object enables routes resolving via the API. In that case, getPreviewSession should return document.url if not linkResolver does not resolve.
```javascript
const api = await Prismic.api({ routes: [{ type: 'page', path: '/:uid'}] })
const previewResolver = await api.getPreviewResolver(token, documentId)
const url = await previewResolver.resolve(null, '/')
console.log({ url }) // /some-uid or /
```
> preview-resolver: use linkResolver or return document.url

- package.json
- src/client.ts
When using the `Client` interface, it seems we never overrides the ref with the preview token.
This causes some trouble mainly when previewing unpublished documents (not redirected to the right page).
> Fix getPreviewResolver

- src/client.ts
- test/__testutils__/createMockQueryHandler.ts
- test/__testutils__/createMockRepositoryHandler.ts
- test/__testutils__/isValidAccessToken.ts
- test/client-buildQueryURL.test.ts
- test/client-getRepository.test.ts
This PR replaces the Authorization header with the `access_token` URL parameter to authenticate requests. It includes temporary comments to restore Authorization header use when the API is ready.
The REST API currently does not fully support the Authorization header for the following reasons:
- **CORS**: CORS preflight requests fail either due to the Authorization header not being sent or an invalid CORS server configuration.
- **CDN Support**: Some repositories do not support the Authorization header on the CDN endpoints.
Related internal issue: https://github.com/prismicio/issue-tracker-wroom/issues/351
> fix: use access_token URL parameter over Authorization header

- src/client.ts
- test/__testutils__/createMockQueryHandler.ts
- test/__testutils__/createQueryResponse.ts
- test/__testutils__/createQueryResponsePages.ts
- test/__testutils__/createRepositoryResponse.ts
- test/__testutils__/isValidAccessToken.ts
- test/__testutils__/types.ts
- test/client-buildQueryURL.test.ts
- test/client-getRepository.test.ts
This moves the access token from a URL parameter to the Authorization header. The header is the preferred authorization strategy.
🚙
> feat: use authorization header for access token

- src/client.ts
- test/client-getAllByEveryTag.test.ts
- test/client-getAllBySomeTags.test.ts
- test/client-getByEveryTag.test.ts
- test/client-getBySomeTags.test.ts
- Adds `getBySomeTags` and `getAllBySomeTags`. They query for documents with at least one of the given tags.
- Renames `getByTags` and `getAllByTags` to `getByEveryTag` and `getAllByEveryTag`. They query for documents with all of the given tags.
> feat: add `getBySomeTags`, rename `getByTags` to `getByEveryTag`

- src/client.ts
- test/client.test.ts
This PR adds a check to ensure a Prismic Rest API V2 endpoint is provided.
It throws an error on client creation if the following criteria is met:
1. A `prismic.io` domain is used.
2. The endpoint does not contain `/api/v2`.
3. `process.env.NODE_ENV` is `development`.
If a custom domain is used (such as through a proxy), no check is performed since we cannot easily see which API version it implements.
Related issue: #200
> feat: ensure Prismic Rest API V2 endpoint is used

- src/ApiSearchResponse.ts
- src/client.ts
- src/documents.ts
I added the possibility to type the data inside Document, if not added, default still any.
```ts
type Post = {
title: RichTextBlock[];
content: RichTextBlock[];
}
const response = await prismic.query<Post>(
[Prismic.predicates.at("document.type", "post")],
{
pageSize: PAGE_SIZE,
graphQuery: `{
post {
title
content
}
}`,
}
);
```
> chore(types): allow gerenic on `Document.data` #204

- examples/custom-timeout/README.md
- examples/custom-timeout/index.js
- examples/custom-timeout/package.json
This PR adds an example demonstrating how to add a custom request timeout duration. It implements it using an AbortController and `setTimeout()`.
See: #129
🐢
> chore: add custom-timeout example

- src/client.ts
- test/client-resolvePreviewUrl.test.ts
Preview only works for the default language, fetch the preview document for all languages. Otherweise getByID will crash before calling the linkResolver
> fix: resolve previewed document URL any language

- examples/custom-caching/index.js
- examples/with-express/index.js
The `.json()` cannot be resolved more than once for the same request
Fix caching example mentioned https://github.com/prismicio/prismic-client/issues/217
> docs: fix caching example by using `.clone()` method

- src/client.ts
- test/client-getAllByTag.test.ts
- test/client-getByTag.test.ts
This PR resolves the following API error when error when using tag methods with a single tag.
```
'document.tags' expected a [list] of 'string' literals... [truncated]
```
This error is returned by the API when using a tag method like the following:
```ts
// API error
client.getAllByTag('tag')
```
After this PR, this now works:
```ts
// Works
client.getAllByTag('tag')
```
This is resolved by ensuring tag methods always use an array predicate parameter, even for single tag queries.
**Note**: This PR also changes `getByTag()` and `getAllByTag()` to use the `any` predicate rather than `at`. This allows matches against documents that have multiple tags.
Fixes: #215
🐱
> fix: resolve `'document.tags' expected a [list] of 'string' literals` error when using tag methods with a single tag

- src/client.ts
- src/lib/minifyGraphQLQuery.ts
- src/lib/removeGraphQLQueryWhitespace.ts
- test/client-graphqlFetch.test.ts
GraphQL queries resolved by `graphqlFetch()` should be minified by removing whitespace wherever possible. This PR adds this functionality.
Note that `graphqlFetch()` is still considered experimental. Its functionality and API may change.
🐻
> fix: minify GraphQL queries by removing whitespace

- README.md
- examples/custom-caching/index.js
- examples/custom-timeout/index.js
- examples/multiple-languages/index.js
- examples/releases/index.js
- examples/server-usage/index.js
- examples/using-refs/index.js
- examples/with-express/index.js
- examples/with-typescript/index.ts
- src/client.ts
- test/client.test.ts
This PR adds support for providing a repository name to `createClient()` in place of an API endpoint.
```ts
import { createClient } from "@prismicio/client";
const client = prismic.createClient("repo-name");
```
Passing an API endpoint is still supported:
```ts
import { createClient } from "@prismicio/client";
const endpoint = prismic.getRepositoryEndpoint("repo-name");
const client = prismic.createClient(endpoint);
```
If the first argument for `createClient()` is not an endpoint, it will build one using `getRepositoryEndpoint()` automatically.
This takes advantage of the `isRepositoryEndpoint()` helper introduced in #222.
Related: https://github.com/prismicio/prismic-helpers/issues/42
🦄
> feat: support providing a repository name to `createClient()` in place of an API endpoint

- src/client.ts
- test/client-resolvePreviewUrl.test.ts
This PR fixes a bug where `resolvePreviewURL()` could return `null` (or some non-string value) in certain cases. This can happen if the provided Link Resolver does not return a string for a particular document. Note that it is valid for a Link Resolver to return a non-string value or choose to not handle certain document types, but `resolvePreviewURL()` requires a string value since a URL is required.
With this PR, `resolvePreviewURL()` will return the given `defaultURL` argument if the resolved URL is not a string.
Fixes: #225
🐛
> fix: return the default URL when `resolvePreviewURL()` does not resolve to a string URL

- src/client.ts
This PR adds types for the `limit` parameter to all `getAll*()` methods.
Before this PR, only `dangerouslyGetAll()` was property typed to accept the `limit` param. All `getAll*()` methods accepted the `limit` param at runtime.
Fixes #233
🐔
> fix: add `limit` to all `getAll*()` methods (fixes #233)

- src/client.ts
- test/client.test.ts
This PR changes an existing check to ensure a Prismic Rest API V2 endpoint is used.
Before this PR, the client would throw an error on instantiation if it detected a non-V2 endpoint _only in development_. The check now happens in any environment other than production, including tests.
Detecting the production environment is done by evaluating `process.env.NODE_ENV !== "production"`.
🐤
> fix: throw when given a non-V2 Prismic Rest API in all non-production environments

- src/client.ts
- test/client-dangerouslyGetAll.test.ts
This PR optimizes `pageSize` when a `limit` is given that is less than `pageSize`.
Before this PR, `pageSize` would always be the given value or the default (`100`). This means more documents may be fetched than needed to satisfy the `limit` param.
Closes: #232
> fix: optimize `pageSize` when a `limit` less than `pageSize` is given

- src/client.ts
- src/lib/getCookie.ts
- src/types.ts
- test/client-resolvePreviewUrl.test.ts
- test/client.test.ts
This PR adds support for [Web API Request](http://developer.mozilla.org/en-US/docs/Web/API/Request) objects containing a [Web API Headers](http://developer.mozilla.org/en-US/docs/Web/API/Headers) instance. Frameworks like SvelteKit use this API rather than an Express-style request object which, unlike the Web API counterpart, contains plain-object-based data.
```typescript
import * as prismic from "@prismicio/client";
const headers = new Headers();
headers.set("cookie", `io.prismic.preview=abc123`);
const request = {
headers,
url: 'https://example.com/preview?documentId=abc123&token=abc123'
};
const client = prismic.createClient("qwerty");
client.enableAutoPreviewsFromReq(request);
// The client will automatically read the `io.prismic.preview` cookie
// and URL parameters to enable …
```
> feat: accept Web API Request object in `enableAutoPreviewsFromReq()`

- src/predicate.ts
- test/predicate-not.test.ts
`not` predicate type was not aligned with API expectations, see: https://github.com/prismicio/prismic-types/issues/35
PR: https://prismicio-docs-v3.prismic.io/documents~w=rest%20api%20technical&b=working&c=release%3AYo3rmxIAACMAlRcT&l=en-us/X7vlhRIAACYAdOzP/?section=Page%20Content
> fix: accept an array of strings when using the `not` predicate type

- src/client.ts
- src/types.ts
- test/client-resolvePreviewUrl.test.ts
This PR fixes a bug where Next.js requests were treated as Web API Requests. This caused the `resolvePreviewURL()` method to throw an error on this line:
https://github.com/prismicio/prismic-client/blob/7a1f2466d2a3e8060a85df8f2fc70aa6e56764aa/src/client.ts#L1220-L1221
In a Next.js request, the `url` property is not a valid URL; it is just the pathname and search params (e.g. `/foo?documentId=bar`).
In a Web API Request object, the `url` property is a valid URL.
(Thanks to @awilderink for pointing this out [here](https://github.com/prismicio/prismic-client/commit/66e01b96e377881e796ec5c034bd3e045bba43b6#r74896683).)
> fix: correctly detect HTTP requests with parsed queries

- src/client.ts
- test/client-getTags.test.ts
This PR fixes an issue where a client's `getTags()` method could return an empty array (`[]`) rather than a list of the repository's tags. This could happen when a repository is proteted with an access token.
This happens because the client's access token was not being sent to the Tags API. This PR ensures the access token is sent if the Tags API is used.
Fixes #243
🐤
> fix: resolve issue where `getTags()` returned an empty array for secured repositories

- examples/with-typescript/index.ts
- examples/with-typescript/types.ts
- src/client.ts
- src/index.ts
- src/types.ts
- test/__testutils__/createClient.ts
This PR adds the ability to declare document types queryable by the client.
Client methods that accept an explicit document type, such as `getByType()` and `getSingle()`, can automatically return the appropriate document type. Furthermore, these methods are typed to only accept document type IDs that have been provided to the client.
```typescript
import * as prismic from "@prismicio/client";
import * as prismicT from "@prismicio/types";
type PageDocument = prismicT.PrismicDocument<
{ foo: prismicT.KeyTextField },
"page"
>;
type SettingsDocument = prismicT.PrismicDocument<
{ bar: prismicT.BooleanField },
"settings"
>;
type AllDocumentTypes = PageDocument | SettingsDocument;
const client = prismic.createClient<AllDocumentTypes>("qwerty");
//    ^ Contains references to document types
const …
```
> feat: declare document TypeScript types in `createClient()`

- src/client.ts
- src/types.ts
This PR fixes a bug where `AbortSignalLike` was incompatible with the native `AbortSignal` type.
The following TypeScript error is emitted when using the native `AbortSignal` type:
```
[tsserver 2739] [E] Type 'AbortSignal' is missing the following properties from type 'AbortSignalLike': reason, throwIfAborted
```
`globalThis.fetch` uses an `AbortSignal` type within the `typescript/lib/lib.dom.d.ts` module that contains properties not present in the `@types/node/globals.d.ts` module. In practice, the wider type from `@types/node/global.d.ts` is sufficient and better integrates with real projects.
🦆
> fix: adjust `AbortSignalLike` to support native `AbortSignal`

- src/client.ts
- test/client-getByID.test.ts
- test/client-getByUID.test.ts
- test/client-getFirst.test.ts
- test/client-getSingle.test.ts
- test/client-resolvePreviewUrl.test.ts
This PR optimizes `getFirst()` by defaulting to only query one document. It does this by setting `pageSize=1`.
The following methods also benefit from this optimization since they use `getFirst()` within their implementation:
- `getByID()`
- `getByUID()`
- `getSingle()`
- `resolvePreviewURL()`
**Exceptions to this optimization**:
- If a `page` param is provided, `pageSize` is not set. `pageSize` affects the behavior of `page`, so we cannot automatically set `pageSize` to 1.
- If a `pageSize` param is provided, it takes priority.
🐥
> refactor: optimize `getFirst()` and dependent methods

- src/buildQueryURL.ts
- src/client.ts
- src/index.ts
- src/types.ts
- test/buildQueryURL.test.ts
- test/client.test.ts
This PR adds support for Route Resolver's recently added `uid`, `lang`, and `brokenRoute` options. Route Resolver definitions can be provided to `@prismicio/client`'s `routes` option.
```typescript
import * as prismic from "@prismicio/client";
const client = prismic.createClient("your-repo-name", {
routes: [
{
type: "page",
uid: "home",
path: "/",
},
{
type: "page",
path: "/:uid",
},
],
brokenRoute: "/404",
});
```
Closes #257.
The `uid` option allows a route to be scoped to a document with a specific UID.
In the following example, a Page document with a UID of `home` will result in a `/` path. All other Page documents will use a computed path of `/:uid`.
```json
[
{
"type": "page",
"uid": "home",
"path": "/"
},
{
"type": "page",
"path": "/:uid"
}
]
```
The `lang` option allows a route to …
> feat: support Route Resolver `uid`, `lang`, and `brokenRoute` options

- package-lock.json
- package.json
- vitest.config.ts
This PR upgrades all dependencies except the following:
- `prettier-plugin-jsdoc`: An ESM-related issue with its underlying `mdast-util-from-markdown` dependency breaks the Prettier plugin. For now, the plugin should be kept on `^0.3`.
**Related issue**: https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/173
🦭
> chore(deps): upgrade dependencies

- src/types.ts
This PR widens `AbortSignal`'s type to support a wider range of `fetch()` implementations.
Unfortunately, a common type among `fetch()` implementations could not be found, so **the `signal` parameter is now typed as `any`**.
Fixes: #254
🐴
> fix: widen `AbortSignal` for greater support of fetch implementations

- .github/workflows/ci.yml
- src/helpers/asLink.ts
- test/__testutils__/testAnyGetMethod.ts
This PR runs type tests across various version of TypeScript (4.5 through 4.9).
It fixes the few errors pointed out by those new tests.
- A minor constructor error
- Exceptionally uses `@ts-ignore` instead of `@ts-expect-error` for a specific TypeScript 4.9 issue (not sure about it, but apparently https://github.com/microsoft/TypeScript/issues/51501 got fixed on the upcoming 5.0 version, someone suggested to backport it to 4.9 but for now it has been ignored)
This PR also refactors a bit the CI architecture to accommodate those new tests. It's a bit more complex but about as fast when not running `size-limit` and faster when running it.
Resolves: #274
> ci: run type tests against various TypeScript version

- src/buildQueryURL.ts
- src/createClient.ts
- src/helpers/documentToLinkField.ts
This PR introduces undocumented support for Node.js 12. Although Node.js 12 is already past its end-of-life (EOL), with Node.js 14's EOL coming within the next month, some developers are still using build systems that do not recognize all Node.js 14 features.
Specifically in `@prismicio/client`, the use of the nullish coelescing operator (`??`) throws errors in older build systems (think: a Babel configuration that isn't aware of the operator).
This PR removes all use of `??` and replaces it with `||` or a nullish ternary check where appropriate.
This PR does **not** mean we officially support Node.js 12. We officially only support LTS versions of Node.js. However, because the change in the PR is simple, we can make an exception in this case.
🐁
> fix: add soft support for Node.js 12

- src/getToolbarSrc.ts
- src/index.ts
- test/getToolbarSrc.test.ts
This PR adds a `getToolbarSrc()` helper that returns a Prismic repository's Prismic Toolbar script URL.
```typescript
import * as prismic from "@prismicio/client";
const toolbarSrc = prismic.getToolbarSrc("my-repo-name");
// => https://static.cdn.prismic.io/prismic.js?new=true&repo=my-repo-name
```
This helper will replace `@prismicio/react`'s `<PrismicToolbar>` when used in React Server Components environments; in Server Components environments, `<script>` elements should be rendered on the server, which `<PrismicToolbar>` is not able to do.
Providing `getToolbarSrc()` allows a developer to get the Prismic Toolbar's script URL and render the `<script>` using their framework's conventions. In a Next.js app, for example, a developer would use `next/script`.
```tsx
import * as prismic from …
```
> feat: add `getToolbarSrc()` helper

- src/createClient.ts
- test/client-resolvePreviewUrl.test.ts
This PR adds support for automatic preview support using Web API `Request`s containing partial URLs.
As an example, Next.js provides a `Request` instance to [Route Handlers](https://beta.nextjs.org/docs/routing/route-handlers). Its `url` property only contains the pathname and search paramters (e.g. `/foo?bar=baz`).
🐟
> feat: support Web API `Request`s containing partial URLs

- src/helpers/asHTML.ts
- src/helpers/asImagePixelDensitySrcSet.ts
- src/helpers/asImageSrc.ts
- src/helpers/asImageWidthSrcSet.ts
- src/helpers/asLink.ts
- src/helpers/asText.ts
- test/helpers-asHTML.test.ts
- test/helpers-asLink.test.ts
- test/helpers-asText.test.ts
> refactor(helpers): standardize helpers interface

- src/createClient.ts
- test/__testutils__/testConcurrentMethod.ts
- test/client-get.test.ts
- test/client-getRepository.test.ts
This PR reverts #285.
#285 was motivated by a need to cache-bust `/api/v2` requests in Next.js apps using its recently-released `fetch()` caching behavior. This strategy ultimately did not work.
The `optimize` parameter should be removed now that it does not have a real-world purpose.
**Note**: This also removes the `x-valid-until` URL parameter that was added to `/api/v2` in #285.
**Note**: This PR retains a bug fix in the concurrent requests logic from from #285.
🐧
> revert: remove `optimize` parameter

- package-lock.json
- package.json
- test/types/customType-boolean.types.ts
- test/types/customType-color.types.ts
- test/types/customType-contentRelationship.types.ts
- test/types/customType-date.types.ts
- test/types/customType-embed.types.ts
- test/types/customType-geoPoint.types.ts
- test/types/customType-group.types.ts
- test/types/customType-image.types.ts
- test/types/customType-integration.types.ts
- test/types/customType-keyText.types.ts
- test/types/customType-link.types.ts
- test/types/customType-linkToMedia.types.ts
- test/types/customType-number.types.ts
- test/types/customType-richText.types.ts
- test/types/customType-select.types.ts
- test/types/customType-sharedSlice.types.ts
- test/types/customType-sharedSliceModel.types.ts
- test/types/customType-sharedSliceModelVariation.types.ts
- test/types/customType-slice.types.ts
- test/types/customType-sliceZone.types.ts
- test/types/customType-timestamp.types.ts
- test/types/customType-title.types.ts
- test/types/customType-uid.types.ts
- test/types/customType.types.ts
For the new feature "Page Types" we need to handle a new property "format".
[DT-1302 - AADev, I need to add the format property to the public prismic-client](https://linear.app/prismic/issue/DT-1302/aadev-i-need-to-add-the-format-property-to-the-public-prismic-client)
A stable release v2 will soon be done, so this PR is to prepare the upgrade with the new format property.
DRAFT because of the alpha but if you're ok to merge the alpha, I'm also ok 😄🤷‍♂️
- ~~My change requires an update to the official documentation.~~
> chore(@prismicio/types-internal): upgrade @prismicio/types-internal dependency

- .size-limit.cjs
- package-lock.json
- package.json
This PR fixes the bug described in https://github.com/prismicio/prismic-typescript-template/pull/27
> fix: properly resolve types when using TypeScript's latest module resolution strategy

- package-lock.json
- package.json
- vite.config.ts
This PR updates all dependencies **except `typescript`**. `msw`'s peer dependencies only allow `typescript@<=5.0`, which is less than the latest `5.1`.
As a side-effect, it fixes CI by updating the version of `@prismicio/client` installed transitively by `@prismicio/mock`.
> chore(deps): update all dependencies

- src/helpers/unstable_mapSliceZone.ts
This PR fixes `unstable_mapSliceZone()`'s return type by only including the following necessary fields:
- `id` (optional)
- `slice_type` (for Rest API V2 Slices)
- `type` (for GraphQL Slices)
Before this PR, `primary`, `items`, etc. from the main `Slice` type were included in each Slice's return type, which is not always going to be the case.
> fix: reduce the return type of `unstable_mapSliceZone()` to only include necessary properties

- src/types/api/repository.ts
- Added a definition for `oauth_token` in `src/types/api/repository.ts`
- Updated `tags` definition in `src/types/api/repository.ts` to be deprecated, mentioned the new location, and linked to the relevant [blog post](https://prismic.io/blog/a-change-to-how-the-prismic-api-handles-tags) outlining the changes.
> docs: Updated tags and oauth_token definitions in repository.ts

- src/createClient.ts
- test/client-getFirst.test.ts
This PR fixes `getFirst()` and all dependent methods, including `getByUID()` and `getByID()`, by throwing a `NotFoundError` when a matching document is not found.
`NotFoundError` is a subclass of `PrismicError`, retaining compatibility with `instanceof PrismicError`.
**Before**:
```ts
import { createClient } from "@prismicio/client";
const client = createClient("example-prismic-repo");
await client.getByUID("page", "non-existent");
// => throws PrismicError
```
**After**:
```ts
import { createClient } from "@prismicio/client";
const client = createClient("example-prismic-repo");
await client.getByUID("page", "non-existent");
// => throws NotFoundError
```
🦁
> fix: throw `NotFoundError` when a document cannot be found

- src/createClient.ts
- test/client.test.ts
This PR adds automatic retry support when Prismic Rest API V2 returns a "429: Too many requests" error response.
The 429 error response can be returned if the API rate limit is exceeded. As of this PR, **the API has a limit of 200 requests per second**.
`@prismicio/client` will automatically retry those requests after enough time has ellapsed to avoid the rate limit. The retry will be transparent from client code, except for the extra wait time.
Code using `@prismicio/client` does not need to change to take advantage of the automatic retry feature.
🦔
> feat: automatically retry rate-limited requests

- src/createClient.ts
- src/errors/PreviewTokenExpired.ts
- src/errors/RepositoryNotFoundError.ts
- src/index.ts
- test/client.test.ts
This PR adds support for two errors in response to the Prismic Document API.
- **`PreviewTokenExpiredError`**: Thrown when a query's preview token (used as a ref) is expired. This error extends from `ForbiddenError` for consistency with [the other ref-related errors](https://github.com/prismicio/prismic-client/pull/327).
- **`RepositoryNotFoundError`**: Thrown when a Prismic repository does not exist. This error was previously thrown as `NotFoundError`. Thus, the new error extends from `NotFoundError` to ensure this change is non-breaking.
The new errors will extend from PrismicError in a future major version for better semantics.
🐤
> fix: support expired preview token and repository not found API error

- src/helpers/mapSliceZone.ts
- src/index.ts
- test/helpers-mapSliceZone.test.ts
- test/index.test.ts
This PR promotes `mapSliceZone` to a stable helper. `unstable_mapSliceZone` should no longer be used.
It also fixes some types for better autocompletion and type checking.
Replace all `unstable_mapSliceZone` imports and uses with `mapSliceZone`.
```diff
- import { createClient, unstable_mapSliceZone } from "@prismicio/client";
+ import { createClient, mapSliceZone } from "@prismicio/client";
const client = createClient("example-prismic-repo");
const page = await client.getByUID("page", "home");
- const mappedSliceZone = unstable_mapSliceZone(
+ const mappedSliceZone = mapSliceZone(
page.data.slices,
{
image: ({ slice }) => ({ url: slice.primary.image.url }),
}
)
```
> feat: stable `mapSliceZone` (previously `unstable_mapSliceZone`)

- src/helpers/mapSliceZone.ts
This PR fixes a type error in `mapSliceZone`. The error was ignored via `// @ts-expect-error` in the source code, but the compiled output removed the comment. Thus, consumers that check the types of the installed package would throw a type error.
The typings have been fixed so `// @ts-expect-error` is no longer used.
> fix: type error in `mapSliceZone`

- CHANGELOG.md
- package-lock.json
- package.json
- src/types/model/contentRelationship.ts
- src/types/model/link.ts
- src/types/model/linkToMedia.ts
- src/types/value/link.ts
- test/types/customType-contentRelationship.types.ts
- test/types/customType-link.types.ts
- test/types/customType-linkToMedia.types.ts
- test/types/fields-contentRelationship.types.ts
- test/types/fields-link.types.ts
- test/types/fields-linkToMedia.types.ts
**Resolves**: [DT-2283](https://linear.app/prismic/issue/DT-2283/aadev-prismic-client-supports-text-in-link-fields)
- Support empty link with text
- Update link config to allow text with a boolean and not a key text config
[^1]:
> support link text with boolean config & empty link

- src/Client.ts
- test/__testutils__/testInvalidRefRetry.ts
- test/client-get.test.ts
- test/client-getAllByEveryTag.test.ts
- test/client-getAllByIDs.test.ts
- test/client-getAllBySomeTags.test.ts
- test/client-getAllByTag.test.ts
- test/client-getAllByType.test.ts
- test/client-getAllByUIDs.test.ts
- test/client-getByEveryTag.test.ts
- test/client-getByID.test.ts
- test/client-getByIDs.test.ts
- test/client-getBySomeTags.test.ts
- test/client-getByTag.test.ts
- test/client-getByType.test.ts
- test/client-getByUID.test.ts
- test/client-getByUIDs.test.ts
- test/client-getFirst.test.ts
- test/client-getSingle.test.ts
**Resolves**: #333
This PR adds a retry mechanism when a `RefNotFoundError` or `RefExpiredError` is thrown in a query method. The client will retry a maximum of 3 times before throwing.
A warning is logged when retrying:
```ts
"The ref (xxx) was expired. Now retrying with the latest master ref (yyy). If you were previewing content, the response will not include draft content."
```
This PR also clears the `/api/v2` value cached for 5s when we know a stale value is saved. This prevents a small edge case where calls within 5s would have all failed if the ref was invalid or expired.
There are no changes to existing code. Queries appear as before.
See the tests.
[^1]: …
> feat: retry invalid/expired refs

- src/types/value/link.ts
- src/types/value/linkToMedia.ts
- test/types/fields-link.types.ts
**Resolves**: #372
Allow link variants to be precisely typed with a generic.
See tests: https://github.com/prismicio/prismic-client/pull/374/files#diff-9557d8ecae877dbbb8ecc6dcfbc29d16d7602d12904e3180aed6918bd6eaad8f
[^1]:
> fix: allow generics with link variant

- src/index.ts
- src/types/value/table.ts
- src/types/value/types.ts
**Resolves**: N/A
This PR exports types related to table fields. `TableField` was already exported, but none of its subtypes were, like `TableFieldDataCell`. The subtypes are helpful in higher-level packages, like `@prismicio/react` and `@prismicio/svelte`.
This PR also updates some of the types with proper namespacing and more accurate descriptions. Because the table field is not publicly available yet, these changes are not considered breaking.
[^1]:
> fix: export table field types

- CHANGELOG.md
- package-lock.json
- package.json
- src/types/value/table.ts
- test/types/fields-table.types.ts
**Resolves**: [DT-2635: \[S\] AADev, I can use the key for each row and cell as a unique identifier](https://linear.app/prismic/issue/DT-2635/[s]-aadev-i-can-use-the-key-for-each-row-and-cell-as-a-unique)
- We need to have a unique key for each row and cell. This would allow us and user to easily map over rows and cells having a unique identifier and prevent hacky things like `JSON.stringify` or using `index`.
[^1]:
> feat: support key for table field content

- src/Client.ts
- src/lib/throttledLog.ts
- test/__testutils__/testInvalidRefRetry.ts
**Resolves**: N/A
This PR prevents the client from logging its retry message many times in succession. The retry message is printed when an invalid or expired ref is tried.
The logger's history is tracked at the module level and will be shared across multiple clients.
The history **will not be shared across multiple processes**, such as during the different stages of a Next.js build. Still, this PR will reduce the total number of logs.
This PR also adds a `[@prismicio/client]` prefix to the retry message, consistent with the client's other logged messages.
This is an example log when building a Next.js website that has a cached expired ref.
```
$ npm run build
> nextjs-starter-prismic-minimal@0.1.0 build
> next build
▲ Next.js 15.1.6
Creating an optimized production build ...
✓ Compiled …
```
> fix: prevent logging the retry message many times

- src/Client.ts
Resolves: #369
This PR removes the `page` parameter from all `getAll*` method params. The `page` parameter was already omitted from most `getAll*` methods, but two methods accidentally included the parameter:
- `getAllByIDs()`
- `getAllByUIDs()`
This was always the intended API, thus this PR is not considered a breaking change.
> [!IMPORTANT]
> This is only an update to the TypeScript types. The client assumes projects are using a type checker like TypeScript or is following each method's documentation. The client does not perform runtime checking.
[^1]:
> fix: omit `page` from all `getAll*` method params

- src/helpers/isFilled.ts
- test/helpers-isFilled.test.ts
- test/types/helpers-isFilled.types.ts
Resolves: N/A
This PR renames `isFilled.integrationField` to `isFilled.integration` to match the naming convention used for other field types in the codebase. The old names (`integrationField` and `integrationFields`) are kept as deprecated aliases to maintain backward compatibility.
The change follows the existing deprecation pattern used throughout the codebase, with proper `@deprecated` JSDoc comments and TODO notes for future removal.
```ts
isFilled.integration(field)
```
1. Verify that `isFilled.integration()` works correctly for checking integration fields
2. Verify that the deprecated `isFilled.integrationField()` still works (aliased to `integration`)
3. Verify that the deprecated `isFilled.integrationFields()` still works (aliased to `integration`)
🚀
[^1]:
Please use these labels …
> fix: rename `isFilled.integrationField` to `isFilled.integration`
